### ISSUE TITLE
What does flag '--test_upscale' do to improve results?

### ISSUE THREAD

**Issue by sjscotti** [chaofengc/Face-SPARNet#10]
Hi 
Your code is terrific!  Thanks so much for publishing it! 
 (BTW, I have also tried your PSFEGAN code, and Face-SPARNet not only produces better results, but it is faster and less memory intensive)
I am using Face-SPARNet to clean up a family group photo with about 100 people in it.  It worked well, and to increase resolution, I originally upscaled the results of Face-SPARNet by 2x using another code (waifu2x-caffe).  Then I noticed that you have a  `--test_upscale` flag in your code.  So I tried running the group photo through your code with `--test_upscale 2`, and the faces were much improved over the results without the flag.  The upscaling flag was not mentioned in your paper as I recall, so I was wondering what you are doing when you upscale to improve the results.
Thanks in advance!

**Comment by chaofengc** [comment]
Thank you for interest. The `--test_upscale` flag simply upsample the whole image and then paste the enhanced faces back to the upsampled image.  This is because faces could be quite small in the original image, and it is difficult to see the difference if we paste the enhanced faces back to very small images.
