### ISSUE TITLE
Some questions about network.

### ISSUE THREAD

**Issue by ComingPeopleHW** [chaofengc/Face-SPARNet#13]
Hi, I find that in models/blocks.py line 130 and 131 ConvLayer do norm and activation function. Is this one of "Differences with the Paper" ? Thank you.

**Comment by chaofengc** [comment]
Thanks for your interest. There should be no big differences between the codes and paper. The parameter number is slightly changed because of slightly different channel numbers. We remove some hard coded channel numbers when rewriting the codes. The norm and activation function is set to `none` type by default.

**Comment by ComingPeopleHW** [comment]
> Thanks for your interest. There should be no big differences between the codes and paper. The parameter number is slightly changed because of slightly different channel numbers. We remove some hard coded channel numbers when rewriting the codes. The norm and activation function is set to `none` type by default.

Thank you!
