### ISSUE TITLE
training set

### ISSUE THREAD

**Issue by cyyycc** [chaofengc/Face-SPARNet#23]
Could you upload the training set? I tried to train the model with the celebA training set, but the effect was far from that in the paper.

**Comment by chaofengc** [comment]
Please refer to https://github.com/chaofengc/Face-SPARNet/issues/21#issuecomment-1084490178

Due to copyright issue, I am not able to provide a permanent download link, here is [the temporal link](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3003628_connect_hku_hk/Ef7siKyLDoVLleMY3zX6PT0BfoE0ROrDSHUCoVdWPV2EzA?e=YdBi89) to the dataset, **please only use it for your own research and do not distribute it**

**Comment by cyyycc** [comment]
> Please refer to [#21 (comment)](https://github.com/chaofengc/Face-SPARNet/issues/21#issuecomment-1084490178)
> 
> Due to copyright issue, I am not able to provide a permanent download link, here is [the temporal link](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3003628_connect_hku_hk/Ef7siKyLDoVLleMY3zX6PT0BfoE0ROrDSHUCoVdWPV2EzA?e=YdBi89) to the dataset, **please only use it for your own research and DO NOT distribute it**

Thank you very much！
